node_dict: './ast_tree.json'
edge_dict: './ast_edge.json'

dataset:
  dataset: './BCB_dataset'
  processed_codes: './Processed_BCB_code'
  # processed_codes: 

  source_codes: 'data.jsonl'
  train: 'train.txt'
  valid: 'valid.txt'
  test: 'test.txt'
  # train: 'valid_dev.txt'
  # valid: 'valid_dev.txt'
  # test: 'valid_dev.txt'
  cache_dir: "./BCB_cache"

  batch_size: 2


model:
  embedding_dim: 128
  hidden_dim: 128

  num_layers: 4
  num_heads: 4

log_dir: "runs"

train:
  epochs: &epochs 20
  max_iter: 2000 # max iteration per epoch

  optimizer:
    type: torch.optim.AdamW
    params:
      lr: 0.0001  
      betas: [0.9, 0.999]  # Mặc định của AdamW
      weight_decay: 0.0005  # Giữ nguyên weight decay

  # optimizer:
  #   type: torch.optim.SGD
  #   params:
  #     lr: 0.001
  #     momentum: 0.9
  #     weight_decay: 0.0005

  # scheduler:
  #   type: torch.optim.lr_scheduler.CosineAnnealingLR
  #   params:
  #     T_max: *epochs
  #     eta_min: 0.00001

  amp: true

