node_dict: './ast_tree.json'
edge_dict: './ast_edge.json'

dataset:
  dataset: './BCB_dataset'
  # processed_codes: './Processed_BCB_code'
  processed_codes: 

  source_codes: 'data.jsonl'
  train: 'train.txt'
  valid: 'valid.txt'
  # train: 'valid_dev.txt'
  # valid: 'valid_dev.txt'
  test: 'test.txt'
  cache_dir: "./BCB_cache"

  batch_size: 2


model:
  num_layers: 2
  embedding_dim: 128
  hidden_dim: 128

  num_layers: 4
  num_heads: 4

log_dir: "runs"

train:
  epochs: &epochs 20
  optimizer:
    type: torch.optim.SGD
    params:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0005
  scheduler:
    type: torch.optim.lr_scheduler.CosineAnnealingLR
    params:
      T_max: *epochs
      eta_min: 0.0001
  amp: true

